### ISSUE TITLE
Enable i2c3 and/or implement orangepi-config?

### ISSUE THREAD

**Issue by scottw-finao** [leeboby/raspberry-pi-os-images#10]
It looks like the Orange Pi zero 3 utilizes i2c3 for the i2c bus. But the default raspi-config seems to enable support for only i2c1 and i2c2 (the latter for the hdmi).  boot config dtoverlay params include an i2c3 enable and a new i2c3-pi5 option but it notes that it is specific to the BCM2711 on the default raspberry pi. (and doesn't appear to work on the orange pi 3 zero)

Is there some way to enable the i2c3 bus on the raspbian image to utilize the i2c capabilities of the orange pi zero 3?  The documentation on the website says to run orangepi-config but even their arch based image does not appear to include this utility. (the documentation appears to be referring to older armbian based orange pi os)

**Comment by scottw-finao** [comment]
I don't know if it can help or not, but it looks like someone named 'Andre Przywara' has submitted a number of sunxi/h618 patches to some arch-based kernel to support the orange pi zero 3. I'm still googling to try to chase down what kernel he is supporting, but there seem to be a number of patches available for the linux kernel including one with references to i2c.

[https://lore.kernel.org/linux-arm-kernel/2691030.mvXUDI8C0e@jernej-laptop/T/](sunxi: Orange Pi Zero 3 DT support)
[https://lore.kernel.org/all/20231020002608.18606-3-andre.przywara@arm.com/T/](sunxi: devicetree updates from Linux v6.6)

**Comment by scottw-finao** [comment]
With more digging, it looks like the i2c is axp313a variant supported by the axp20x kernel driver?  but there are no overlays in /boot/overlay so i can't use dtparam or dtoverlay to probe the overlay file for parameters. (I'm assuming they are compiled internally in the kernel?)

Does anyone know the valid syntax for dtparam values for axp20x, apx20x-i2c and/or apx20x-gpio?

**Comment by deamen** [comment]
The AXP313A is PMIC, i2c3 is a different chip but I don't know what it is.

Don't know which DT the image is using.
As far as I can tell the mainline kernel DT doesn't work , I can enable i2c3 in DT but i2cdetect timed out on it.
> i2c i2c-3: mv64xxx: I2C bus locked, block: 1, time_left: 0

But the other mv64xxx is working, that means the drivers are there maybe just need to get the dts tuned.
># i2cdetect -y 4
>     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
>00:                         -- -- -- -- -- -- -- -- 
>10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>30: -- -- -- -- -- -- UU -- -- -- -- -- -- -- -- -- 
>40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>70: -- -- -- -- -- -- -- -- 

The mainline kernel DT is in linux-v6.6, you will need at least linux-v6.5, the PMIC(AXP313A) driver is in since v6.5

**Comment by scottw-finao** [comment]
I got a response back from Andre but I'm confused how you are implementing DT.  There was no /boot/overlays/ directory and no /boot/cmdline.txt - and I suspect the /boot/config.txt was created when I tried using raspi-config to enable i2c as the only line in it is the one enabling i2c.
I see there is a /boot/dtb/allwinner/overlay directory but the files are all prefixed with sun50i-h616-* -- are these the overlay files for this os?  And how do you configure the boot params?  (if there's a wiki on this somewhere for these images, please feel free to refer me to it)

**Comment by scottw-finao** [comment]
if I'm reading the script properly, you appear to enable the dt overlay files by removing the 'overlay_prefix' and using a list of the suffixes separated by '&'?  Is that correct?  i.e. so if I want to try to enable the `/boot/dtb/allwinner/overlay/sun50i-h616-ph-i2c3.dtbo` file I would use:

```
overlays=ph-i2c3
```

in the /boot/orangepiEnv.txt file?  Is that correct?

I'm not in front of the device at the moment but connecting remotely to it. It seems to push the two existing i2cs to i2c-4 and i2c-5 but it is giving me an i2c-3 device that is showing currently with nothing connected. (I do not currently have anything connected to those two pins)

**Comment by deamen** [comment]
> I got a response back from Andre but I'm confused how you are implementing DT.

What did Andre say? I am hoping to be able to enable i2c3 in the mainline DT.

Thanks

**Comment by scottw-finao** [comment]
First a question then I'll cut/paste what I got back from Andre.  Are the raw dtsi files available somewhere for your dtbo files?

**Comment by scottw-finao** [comment]
This response:

> You don't need to re-configure or recompile the kernel, since the
> Allwinner I2C driver is already in and that can of course drive any I2C
> controller, not just I2C0 or I2C1.
> All you need to do is to enable and configure I2C3 in the devicetree(DT).
> Now we don't enable peripherals that have their pins on generic pinheaders
> in the official DT, since connecting an I2C device there is a *user*
> choice, and other people might want to use them for GPIOs or a UART.
> So would need to deploy the DT change just on your board, which is
> typically done via a DT overlay:
> ===== sun50i-h616-orangepi-zero-i2c3.dtso =====
> /dts-v1/;
> /plugin/;
> 
> &i2c3 {
>         pinctrl-names = "default";
>         pinctrl-0 = <&i2c3_ph_pins>;
>         status = "okay";
> };
> ===============================================
> You can compile this via:
> $ dtc -o sun50i-h616-orangepi-zero-i2c3.dtbo \
>   sun50i-h616-orangepi-zero-i2c3.dtso
> And then apply in U-Boot:
> => fdt move $fdtcontroladdr $fdt_addr_r
> => load mmc0 0:1 $fdtoverlay_addr_r sun50i-h616-orangepi-zero-i2c3.dtbo
> => fdt apply $fdtoverlay_addr_r
> 
> Then use $fdt_addr_r as the DT address.
> 
> If you want an easier, but dirtier solution, you can just put the &i2c3
> node above (minus the dts-v1 and plugin lines) into U-Boot's DT copy of
> arch/arm/dts/sun50i-h616-orangepi-zero.dtsi (or whatever DT you use,
> U-Boot's would be the recommended one). Then rebuild U-Boot (just to
> include this changed .dtb) and "flash" that.
> 
> I do realise that this sounds quite complicated and involved for such a
> simple thing, and I actually have patches to improve the experience: by
> letting a U-Boot command pick all all .dtbo files from a given directory
> and apply them automatically. Hopefully I will find the time to push on
> those patches again.

**Comment by deamen** [comment]
> First a question then I'll cut/paste what I got back from Andre. Are the raw dtsi files available somewhere for your dtbo files?

If you mean what I as doing. I am actually patching the dts file direrctly in the mainline kernel with &i2c3 approach you posted. But I think I am missing a few lines, I will try the code from Andre today.

I have posted the procedure for Orange Pi Zero3, you should be able to find the code in my github repositories:
https://blog.yobibyte.com.au/posts/build-mainline-dtb-orangepi-zero3/
https://blog.yobibyte.com.au/posts/fedora-server-on-orangepi-zero3/

If I get i2c3 working properly I will post a new page and update the code in my relevent github repositories.

**Comment by deamen** [comment]
> This response:

Thanks, I get i2c3 working on Fedora Sever 39:

> i2cdetect -y 3
>     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
>00:                         -- -- -- -- -- -- -- -- 
>10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
>50: -- -- -- -- -- -- -- 57 -- -- -- -- -- -- -- -- 
>60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- -- 
>70: -- -- -- -- -- -- -- --     

The ds3231 RTC is detected:

> [  178.890212] i2c i2c-3: new_device: Instantiated device ds3231 at 0x68
> [  178.945714] rtc-ds1307 3-0068: registered as rtc1

Here is the patch, the aliases part is to ensure i2c3 in Linux is i2c3 on the board, otherwise it get named as i2c0:
```
diff --git a/arch/arm64/boot/dts/allwinner/sun50i-h618-orangepi-zero3.dts b/arch/arm64/boot/dts/allwinner/sun50i-h618-orangepi-zero3.dts
index b3b1b8692125..5f6ea8da9ae5 100644
--- a/arch/arm64/boot/dts/allwinner/sun50i-h618-orangepi-zero3.dts
+++ b/arch/arm64/boot/dts/allwinner/sun50i-h618-orangepi-zero3.dts
@@ -10,6 +10,12 @@
 / {
 	model = "OrangePi Zero3";
 	compatible = "xunlong,orangepi-zero3", "allwinner,sun50i-h618";
+
+	aliases {
+		i2c1 = &i2c1;
+		i2c2 = &i2c2;
+		i2c3 = &i2c3;
+	};
 };
 
 &emac0 {
@@ -87,6 +93,13 @@ reg_dcdc3: dcdc3 {
 	};
 };
 
+&i2c3 {
+        pinctrl-names = "default";
+        pinctrl-0 = <&i2c3_ph_pins>;
+        status = "okay";
+};
+
+
 &pio {
 	vcc-pc-supply = <&reg_dldo1>;
 	vcc-pf-supply = <&reg_dldo1>;
```

The dtbo approach is more flexible, I may look into it as well, but for now I am happy with patching the mainline kernel dts.

**Comment by scottw-finao** [comment]
I got home and was able to confirm the overlays=ph-i2c3 was working. I would still be curious to know why the other two are being pushed up from 0 and 1 to 4 and 5 now, but since I'm not using them, that's only curiosity.  So I 'm 'resolved' but you may want to open another issue regarding apt clobbering your raspi-config and whatever sets the environment variables it uses.  That's bound to lead to more trouble down the road.

**Comment by scottw-finao** [comment]
Wait, i stand corrected - I made a lucky mistake in that it helped me solve my issue, but i accidentally mounted the zero2w image to get the raspi-config executable. The one in your zero3 image appears to be typical raspbian style as-is straight out of the image.  So that's why I was seeing a different configuration than the manual suggests.

**Comment by TadyTheFish** [comment]
For me `overlays=ph-i2c3` does not work.
But `overlays=i2c3-ph` works

**Comment by DarkAxi0m** [comment]
> For me `overlays=ph-i2c3` does not work. But `overlays=i2c3-ph` works Tested on dietpi and armbian

overlays=i2c3-ph work for me too, my device on pins 3&5 showed up with  i2cdetect -y 2
