### ISSUE TITLE
Invalid PDF file

### ISSUE THREAD

**Issue by tik-tak-soft** [leeboby/raspberry-pi-os-images#15]
https://github.com/leeboby/raspberry-pi-os-images/blob/main/OrangePi_Zero2w_H618_RaspiOS_%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C_v1.0.pdf

thanks

**Comment by leeboby** [comment]
https://github.com/leeboby/raspberry-pi-os-images/blob/main/OrangePi_Zero2w_H618_RaspiOS_%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C_v1.1.pdf
